name: sip_ua
version: 0.3.5
description: A SIP UA stack for Flutter/Dart, based on flutter-webrtc, support iOS/Android/Destkop/Web.
homepage: https://github.com/cloudwebrtc/dart-sip-ua
environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  crypto: any
  flutter_webrtc: any
  intl: any
  logger: any
  parser_error: any
  path: any
  random_string: any
  recase: any
  sdp_transform: any
  uuid: any
  

dev_dependencies:
  test: any
